export default {
    SET_ITEM: 'SET_ITEM',
    SET_ITEM_FETCH_STATUS: 'SET_ITEM_FETCH_STATUS',
    SET_ITEM_STEPS: 'SET_ITEM_STEPS',
    SET_STEP_VALUE: 'SET_STEP_VALUE',
    RESET_COMMUNITY_REDUCER: 'RESET_COMMUNITY_REDUCER',
}
